/**
 * This file is generated by genenrate-i18n.mjs
 * Do not edit this file directly
 */
import enMessage from '../../public/_locales/en/messages.json'
import deMessage from '../../public/_locales/de/messages.json'
import zh_CNMessage from '../../public/_locales/zh_CN/messages.json'
import zh_TWMessage from '../../public/_locales/zh_TW/messages.json'

export function getMessageFromLocale(locale: string) {
  switch (locale) {
    case 'en':
      return enMessage
    case 'de':
      return deMessage
    case 'zh_CN':
      return zh_CNMessage
    case 'zh_TW':
      return zh_TWMessage
    default:
      throw new Error('Unsupported locale')
  }
}

export const defaultLocale = (() => {
  const locales = ['en', 'de', 'zh_CN', 'zh_TW']
  const firstLocale = locales[0]
  const defaultLocale = Intl.DateTimeFormat().resolvedOptions().locale.replace('-', '_')
  if (locales.includes(defaultLocale)) {
    return defaultLocale
  }
  const defaultLocaleWithoutRegion = defaultLocale.split('_')[0]
  if (locales.includes(defaultLocaleWithoutRegion)) {
    return defaultLocaleWithoutRegion
  }
  return firstLocale
})()
