import fs from 'node:fs'

const GENERATED_FILE_HEADER = `/**
 * This file is generated by genenrate-i18n.mjs
 * Do not edit this file directly
 */`

/**
 * @url https://developer.chrome.com/docs/extensions/reference/api/i18n#support_multiple_languages
 */
const SUPPORTED_LANGUAGES = {
  ar: 'Arabic',
  am: 'Amharic',
  bg: 'Bulgarian',
  bn: 'Bengali',
  ca: 'Catalan',
  cs: 'Czech',
  da: 'Danish',
  de: 'German',
  el: 'Greek',
  en: 'English',
  en_AU: 'English (Australia)',
  en_GB: 'English (Great Britain)',
  en_US: 'English (USA)',
  es: 'Spanish',
  es_419: 'Spanish (Latin America and Caribbean)',
  et: 'Estonian',
  fa: 'Persian',
  fi: 'Finnish',
  fil: 'Filipino',
  fr: 'French',
  gu: 'Gujarati',
  he: 'Hebrew',
  hi: 'Hindi',
  hr: 'Croatian',
  hu: 'Hungarian',
  id: 'Indonesian',
  it: 'Italian',
  ja: 'Japanese',
  kn: 'Kannada',
  ko: 'Korean',
  lt: 'Lithuanian',
  lv: 'Latvian',
  ml: 'Malayalam',
  mr: 'Marathi',
  ms: 'Malay',
  nl: 'Dutch',
  no: 'Norwegian',
  pl: 'Polish',
  pt_BR: 'Portuguese (Brazil)',
  pt_PT: 'Portuguese (Portugal)',
  ro: 'Romanian',
  ru: 'Russian',
  sk: 'Slovak',
  sl: 'Slovenian',
  sr: 'Serbian',
  sv: 'Swedish',
  sw: 'Swahili',
  ta: 'Tamil',
  te: 'Telugu',
  th: 'Thai',
  tr: 'Turkish',
  uk: 'Ukrainian',
  vi: 'Vietnamese',
  zh_CN: 'Chinese (China)',
  zh_TW: 'Chinese (Taiwan)',
}

const locales = fs
  .readdirSync('locales', { withFileTypes: true })
  .filter(entry => entry.isDirectory())
  .map(entry => entry.name)
  .sort((a, b) => {
    if (a === 'en') return -1
    if (b === 'en') return 1
    return a.localeCompare(b)
  })

locales.forEach(locale => {
  if (!(locale in SUPPORTED_LANGUAGES)) {
    throw new Error(`Unsupported language: ${locale}`)
  }
})

makeTypeFile(locales)
makeGetMessageFromLocaleFile(locales)

function formatFile(lines) {
  return `${lines.join('\n')}\n`
}

function quote(value) {
  return `'${value}'`
}

function getMessageIdentifier(locale) {
  return `${locale}Message`
}

function makeTypeFile(locales) {
  const imports = locales.map(
    locale => `import type ${getMessageIdentifier(locale)} from '../locales/${locale}/messages.json'`,
  )
  const typeFile = formatFile([
    GENERATED_FILE_HEADER,
    ...imports,
    '',
    `export type MessageKey = ${locales.map(locale => `keyof typeof ${getMessageIdentifier(locale)}`).join(' & ')}`,
    '',
    `export type DevLocale = ${locales.map(quote).join(' | ')}`,
  ])

  fs.writeFileSync('lib/type.ts', typeFile)
}

function makeGetMessageFromLocaleFile(locales) {
  const defaultLocaleCode = `(() => {
  const locales = [${locales.map(quote).join(', ')}]
  const firstLocale = locales[0]
  const defaultLocale = Intl.DateTimeFormat().resolvedOptions().locale.replace('-', '_')
  if (locales.includes(defaultLocale)) {
    return defaultLocale
  }
  const defaultLocaleWithoutRegion = defaultLocale.split('_')[0]
  if (locales.includes(defaultLocaleWithoutRegion)) {
    return defaultLocaleWithoutRegion
  }
  return firstLocale
})()`

  const importLines = locales.map(
    locale => `import ${getMessageIdentifier(locale)} from '../locales/${locale}/messages.json'`,
  )
  const switchCases = locales.flatMap(locale => [
    `    case '${locale}':`,
    `      return ${getMessageIdentifier(locale)}`,
  ])

  const getMessageFromLocaleFile = formatFile([
    GENERATED_FILE_HEADER,
    ...importLines,
    '',
    'export function getMessageFromLocale(locale: string) {',
    '  switch (locale) {',
    ...switchCases,
    '    default:',
    "      throw new Error('Unsupported locale')",
    '  }',
    '}',
    '',
    `export const defaultLocale = ${defaultLocaleCode}`,
  ])

  fs.writeFileSync('lib/getMessageFromLocale.ts', getMessageFromLocaleFile)
}
